//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public int branchid { get; set; }
        public string branchname { get; set; }
        public string statusid { get; set; }
        public string org_id { get; set; }
        public string org_ct_id { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddt { get; set; }
        public string editedby { get; set; }
        public Nullable<System.DateTime> editeddt { get; set; }
    }
}
