//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employeeID { get; set; }
        public string staffID { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string surname { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string maritalstatus { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public Nullable<int> stateID { get; set; }
        public Nullable<int> cityID { get; set; }
        public string address { get; set; }
        public string idTypeID { get; set; }
        public string idNumber { get; set; }
        public string kinName { get; set; }
        public string kinPhone { get; set; }
        public string kinAddress { get; set; }
        public string kinRelationshipId { get; set; }
        public string employeeFunctionid { get; set; }
        public Nullable<int> branchID { get; set; }
        public string manager1ID { get; set; }
        public string manager2ID { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddt { get; set; }
        public Nullable<int> countryid { get; set; }
    }
}
