//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lapo_hrEntities : DbContext
    {
        public lapo_hrEntities()
            : base("name=lapo_hrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<function> function { get; set; }
        public virtual DbSet<identification> identification { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<org_unit> org_unit { get; set; }
        public virtual DbSet<org_unit_ref> org_unit_ref { get; set; }
        public virtual DbSet<processref> processref { get; set; }
        public virtual DbSet<relationship> relationship { get; set; }
        public virtual DbSet<roles_ref> roles_ref { get; set; }
        public virtual DbSet<state> state { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<testing> testing { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<employee> employee { get; set; }
    }
}
