//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class org_unit_ref
    {
        public int org_ref_id { get; set; }
        public string org_cat { get; set; }
        public string org_desc { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public string edited_by { get; set; }
        public Nullable<System.DateTime> edited_dt { get; set; }
        public string status_id { get; set; }
    }
}
