//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class relationship
    {
        public int relid { get; set; }
        public string rel_desc { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddt { get; set; }
        public string editedby { get; set; }
        public Nullable<System.DateTime> editeddt { get; set; }
    }
}
