//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class testing
    {
        public string staffid { get; set; }
        public string text { get; set; }
        public Nullable<decimal> number { get; set; }
        public string createdby { get; set; }
    }
}
